language: cpp
dist: xenial
compiler: gcc

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv
      - clang-tidy

jobs:
  include:
    - stage: linux
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt install g++-8 gcc-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
      install:
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories
        - ./setup_environment.sh
# Install conan dependencies, cmake and make
        - mkdir build && cd build
        - conan install .. --build=missing -s compiler.libcxx=libstdc++11
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      script:
        - make -j$(nproc)
        - make test
        - python3 ../run-clang-tidy.py -header-filter='.*' -checks='*'
