language: cpp
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-pip
      - python3-venv
      - clang-tidy
      - g++-8
      - gcc-8
      - lcov
      - valgrind
      - libva2
        #- libxcb-shape0-dev
        #- libgl1-mesa-dev
        #- libglu1-mesa-dev

jobs:
  include:
    - stage: linux
      install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories
        - ./setup_environment.sh

      env:
        - BUILD_TYPE=Debug

      before_script:
# Install conan dependencies cmake and make
        - mkdir build && cd build
        - cmake -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

      script:
        - make -j$(nproc)
        - cd bin
        - ./run_tests.sh
        - cd ..
        - lcov --directory . --capture --output-file coverage.info         # capture coverage info
        - lcov --remove coverage.info '/usr/*' '/home/*/.conan/*' --output-file coverage.info # filter out system
        - lcov --list coverage.info                                        # debug info
        - valgrind --error-exitcode=42 --leak-check=full ./bin/tst*
        - python3 ../run-clang-tidy.py -header-filter='.*' -checks='*'
